name: build_validation

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  validate-code:
    name: job for validating code and structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Load all build validation related dependencies
        shell: bash
        run: |
          set -e # fail on error
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Execute Unit Tests
        shell: bash
        run: |
          pytest . --cov=. --cov-report=html

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "htmlcov/**"
