name: rag_exp_acc_ci.yml

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/development' && github.ref != 'refs/heads/main' }}

jobs:
  execute-code-and-check:
    env:
      AZURE_SEARCH_ADMIN_KEY: ${{ secrets.AZURE_SEARCH_ADMIN_KEY }}
      AZURE_SEARCH_SERVICE_ENDPOINT: ${{ secrets.AZURE_SEARCH_SERVICE_ENDPOINT }}
      AZURE_LANGUAGE_SERVICE_KEY: ${{ secrets.AZURE_LANGUAGE_SERVICE_KEY }}
      AZURE_LANGUAGE_SERVICE_ENDPOINT: ${{ secrets.AZURE_LANGUAGE_SERVICE_ENDPOINT }}      
      OPENAI_API_TYPE: "azure"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
      OPENAI_ENDPOINT: ${{ secrets.OPENAI_ENDPOINT }}
      AML_RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      AML_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      AML_WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
    name: code validation through execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
      - name: execute index creation step
        shell: bash
        run: |
          python 01_index.py --data-directory-name='data-ci'
      - name: execute qna step
        shell: bash
        run: |
          python 02_qa_generation.py  
      - name: execute querying step
        shell: bash
        run: |
          python 03_querying.py  
      - name: execute evaluation step
        shell: bash
        run: |
          python 04_evaluation.py
